#falta deploy, ver evento de pr, jobs paralelos, ver que test dejo o agrego

name: Pipeline de prueba

on:
  push:
    branches: [ "main" ]

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm install
    - name: Lint
      run: npm run lint

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm install
    - name: build
      run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  Test:
    needs: [Linter, Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm install
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Test unitario
      run: npm run test

   

  Deploy:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: instalar dependencias
      run: npm install
    - name: deploy
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
    - name: Notificar éxito de deploy
      if: success()  
      uses: slackapi/slack-github-action@v1.22.0
      with:
        webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
        slack-message: "El deploy ha sido exitoso :white_check_mark: en el repositorio ${GITHUB_REPOSITORY} en la rama ${GITHUB_REF} por ${GITHUB_ACTOR}."
      
  E2E_Test:
    needs: [Deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm install
    - name: Test de Cypress en modo headless #sin interfaz grafica, npx wait-on https://continuous-integration-rbne.onrender.com 
      run: |
        npm run cypress:run