name: Pipeline de prueba

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: 18
    - name: Instalar dependencias
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test de Cypress en modo headless
      run: |
        npx serve dist -l 3000 &
        npx wait-on http://localhost:3000
        npm run cypress:run


